name: ds_button
description: A simple, ds to use, and customizable progress/loading Flutter Button_ that supports variety of button styles (elevated, outlined, text).
version: 0.0.1+1
homepage: https://github.com/jheimes-silveira/ds_button

environment:
  sdk: ">=2.18.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
